import type { Metadata } from "next";
import { Raleway, Playfair_Display } from 'next/font/google'
import './globals.css'

const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway', display: 'swap' })
const playfairDisplay = Playfair_Display({ subsets: ['latin'], variable: '--font-playfair-display', display: 'swap' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${playfairDisplay.variable} ${raleway.variable} antialiased`}>
        <header></header>

        <main>
          <div className='container-web'>{children}</div>
        </main>

        <footer></footer>
      </body>
    </html>
  )
}
